spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/db
        username: postgres
        password: password
        driver-class-name: org.postgresql.Driver
    jpa:
        spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect